/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Controller.ControllerClassification;
import java.awt.Cursor;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableModel;
//import org.jfree.chart.ChartFactory;
//import org.jfree.chart.ChartFrame;
//import org.jfree.chart.ChartPanel;
//import org.jfree.chart.JFreeChart;
//import org.jfree.chart.plot.CategoryPlot;
//import org.jfree.chart.plot.PlotOrientation;
//import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author RIDWAN
 */
public class FormClassification extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewClassification2
     */
    public FormClassification() {
        initComponents();
        setLocation(15, 20);
        initialization();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jYearChooser1 = new com.toedter.calendar.JYearChooser();
        jYearChooser2 = new com.toedter.calendar.JYearChooser();
        txtFileDirectory = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNumberOfK = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        labelPilihFile = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePreview = new javax.swing.JTable();
        labelPesanError = new javax.swing.JLabel();
        labelJumlahData = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        buttonProses = new javax.swing.JButton();
        buttonReset = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableResult = new javax.swing.JTable();
        buttonSimpan = new javax.swing.JButton();
        buttonReClass = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labelSiswaLULUS = new javax.swing.JLabel();
        labelSiswaTIDAK = new javax.swing.JLabel();
        labelKeterangan = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Klasifikasi Kelulusan Ujian Nasional Siswa");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/title-klasifikasi.png"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(1340, 697));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/button-browse.png"))); // NOI18N
        jButton1.setText("Browse...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("/");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Number of Nearest Neighbor (k) : ");

        txtNumberOfK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumberOfKActionPerformed(evt);
            }
        });
        txtNumberOfK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumberOfKKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Tahun Ajaran :");

        labelPilihFile.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelPilihFile.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelPilihFile.setText("Pilih File :");

        tablePreview.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIS", "NAMA", "JK", "MTK1", "BINDO1", "BING1", "IPA1", "MTK2", "BINDO2", "BING2", "IPA2", "HASILTO"
            }
        ));
        jScrollPane1.setViewportView(tablePreview);

        labelPesanError.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelPesanError.setForeground(new java.awt.Color(204, 0, 0));
        labelPesanError.setText("<<Tampil Pesan Error>>");

        labelJumlahData.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelJumlahData.setForeground(new java.awt.Color(0, 153, 51));
        labelJumlahData.setText("0 Data");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Jumlah Data : ");

        jCheckBox1.setText("Kriteria Manual");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        buttonProses.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buttonProses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/button-procces.png"))); // NOI18N
        buttonProses.setText("Proses Klasifikasi");
        buttonProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProsesActionPerformed(evt);
            }
        });

        buttonReset.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buttonReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/button-reset.png"))); // NOI18N
        buttonReset.setText("Reset");
        buttonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(labelPilihFile)
                                .addGap(6, 6, 6)
                                .addComponent(txtFileDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jButton1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jYearChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel1)
                                .addGap(6, 6, 6)
                                .addComponent(jYearChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNumberOfK, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelPesanError)
                                .addGap(187, 187, 187)
                                .addComponent(buttonProses)
                                .addGap(18, 18, 18)
                                .addComponent(buttonReset))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelJumlahData, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1527, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jCheckBox1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jYearChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(jYearChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)))
                        .addGap(6, 6, 6)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(labelPilihFile))
                    .addComponent(txtFileDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(txtNumberOfK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelPesanError)
                                .addComponent(buttonProses, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(labelJumlahData))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Klasifikasi Kelulusan UN Siswa", jPanel1);

        tableResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIS", "Nama", "JK", "MTK1", "BINDO1", "BING1", "IPA1", "MTK2", "BINDO2", "BING2", "IPA2", "HASILTO", "HASILUN"
            }
        ));
        jScrollPane2.setViewportView(tableResult);

        buttonSimpan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buttonSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/button-save.png"))); // NOI18N
        buttonSimpan.setText("Simpan");
        buttonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanActionPerformed(evt);
            }
        });

        buttonReClass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buttonReClass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/button-reclass.png"))); // NOI18N
        buttonReClass.setText("Klasifikasi Ulang");
        buttonReClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonReClassActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detail Klasifikasi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Siswa Terklasifikasi TIDAK LULUS :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Siswa Terklasifikasi LULUS :");

        labelSiswaLULUS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelSiswaLULUS.setText("0");

        labelSiswaTIDAK.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelSiswaTIDAK.setText("0");

        labelKeterangan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelKeterangan.setText("Hasil Klasifikasi Kelulusan UN Siswa Pada Tahun Ajaran <<tahun ajaran>>, dengan paramater K = <<nilai k>> adalah sebagai berikut :");

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/button-chart.png"))); // NOI18N
        jButton5.setText("Tampilkan Grafik");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Siswa");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Siswa");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(labelKeterangan))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(labelSiswaTIDAK)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(labelSiswaLULUS)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(396, 396, 396)
                        .addComponent(jButton5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(labelKeterangan)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelSiswaLULUS)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelSiswaTIDAK)
                            .addComponent(jLabel8))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonReClass))
                .addGap(94, 94, 94)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1518, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(buttonSimpan)
                        .addGap(18, 18, 18)
                        .addComponent(buttonReClass))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 90, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Hasil Klasifikasi Kelulusan UN Siswa", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        ControllerClassification controllerClassification = new ControllerClassification();
        controllerClassification.showChart(labelSiswaLULUS, labelSiswaTIDAK, labelKeterangan);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void buttonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanActionPerformed
        try {
            // TODO add your handling code here:
            ControllerClassification controllerClassification = new ControllerClassification();
            controllerClassification.saveResultFile(jYearChooser1, jYearChooser2, tableResult);
        } catch (IOException ex) {
            Logger.getLogger(FormClassification.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonSimpanActionPerformed

    private void buttonReClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonReClassActionPerformed
        // TODO add your handling code here:
        txtNumberOfK.requestFocus();
        DefaultTableModel tabModeRes = (DefaultTableModel) tableResult.getModel();
        tabModeRes.setRowCount(0);
        buttonSimpan.setEnabled(false);
        buttonReClass.setEnabled(false);
        jPanel5.setVisible(false);
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_buttonReClassActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void txtNumberOfKKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumberOfKKeyTyped
        // TODO add your handling code here:
        ControllerClassification controllerClassification = new ControllerClassification();
        controllerClassification.validasiNumberofNearest(evt, txtNumberOfK, labelPesanError);
    }//GEN-LAST:event_txtNumberOfKKeyTyped

    private void txtNumberOfKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumberOfKActionPerformed
        // TODO add your handling code here:
        ControllerClassification controllerClassification = new ControllerClassification();
        controllerClassification.processMining(txtNumberOfK, tablePreview, labelPesanError, tableResult, labelSiswaLULUS, labelSiswaTIDAK, labelKeterangan, jYearChooser1, jYearChooser2, jTabbedPane1);
        buttonSimpan.setEnabled(true);
        buttonReClass.setEnabled(true);
        jPanel5.setVisible(true);
    }//GEN-LAST:event_txtNumberOfKActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            ControllerClassification controllerClassification = new ControllerClassification();
            controllerClassification.chooseFile(evt, txtFileDirectory, txtNumberOfK, labelJumlahData, buttonProses, tablePreview);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Problem while upload file!", "Informasi Kesalahan Upload", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buttonProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProsesActionPerformed
        // TODO add your handling code here:

        if (jCheckBox1.isSelected()) {

        } else {
            ControllerClassification controllerClassification = new ControllerClassification();
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            controllerClassification.processMining(txtNumberOfK, tablePreview, labelPesanError, tableResult, labelSiswaLULUS, labelSiswaTIDAK, labelKeterangan, jYearChooser1, jYearChooser2, jTabbedPane1);
            this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        }
        buttonSimpan.setEnabled(true);
        buttonReClass.setEnabled(true);
        jPanel5.setVisible(true);
        //        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_buttonProsesActionPerformed

    private void buttonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResetActionPerformed
        // TODO add your handling code here:
        tablePreview.setModel(new javax.swing.table.DefaultTableModel(
            new Object[][]{},
            new String[]{
                "NIS", "Nama", "JK", "MTK1", "BINDO1", "BING1", "IPA1", "MEANTO1", "MTK2", "BINDO2", "BING2", "IPA2", "HASILTO"
            }
        ));
        initialization();
    }//GEN-LAST:event_buttonResetActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonProses;
    private javax.swing.JButton buttonReClass;
    private javax.swing.JButton buttonReset;
    private javax.swing.JButton buttonSimpan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private com.toedter.calendar.JYearChooser jYearChooser1;
    private com.toedter.calendar.JYearChooser jYearChooser2;
    private javax.swing.JLabel labelJumlahData;
    private javax.swing.JLabel labelKeterangan;
    private javax.swing.JLabel labelPesanError;
    private javax.swing.JLabel labelPilihFile;
    private javax.swing.JLabel labelSiswaLULUS;
    private javax.swing.JLabel labelSiswaTIDAK;
    private javax.swing.JTable tablePreview;
    private javax.swing.JTable tableResult;
    private javax.swing.JTextField txtFileDirectory;
    private javax.swing.JTextField txtNumberOfK;
    // End of variables declaration//GEN-END:variables

    private void initialization() {
        txtFileDirectory.setEditable(false);
        buttonProses.setEnabled(false);
        txtNumberOfK.setEnabled(false);
        labelPesanError.setText("");
        buttonSimpan.setEnabled(false);
        buttonReClass.setEnabled(false);
        jPanel5.setVisible(false);
        jCheckBox1.setVisible(false);
    
    }

   
    private double[][] getDataValue(int rowCountData, JTable tablePreview) {
        double[][] returnValue = new double[rowCountData][3];
        double transHasilTO = 0;
        for (int i = 0; i < rowCountData; i++) {
            if (tablePreview.getValueAt(i, 8).equals("LULUS")) {
                transHasilTO = 1.0;
            } else if (tablePreview.getValueAt(i, 8).equals("TIDAK")) {
                transHasilTO = 0.0;
            }
            returnValue[i][0] = Double.parseDouble(tablePreview.getValueAt(i, 3).toString()) / 4;
            returnValue[i][1] = (Double.parseDouble(tablePreview.getValueAt(i, 4).toString())
                    + Double.parseDouble(tablePreview.getValueAt(i, 5).toString())
                    + Double.parseDouble(tablePreview.getValueAt(i, 6).toString())
                    + Double.parseDouble(tablePreview.getValueAt(i, 7).toString())) / 4;
            returnValue[i][2] = transHasilTO;
        }
        return returnValue;
    }

 

    private void tampilKeTabel(String[] finalClass, int rowCountData) {
        DefaultTableModel tableModelResult = new DefaultTableModel();
        tableModelResult = (DefaultTableModel) tableResult.getModel();
        int jumlahSiswaLULUS = 0;
        int jumlahSiswaTIDAK = 0;
        for (int i = 0; i < rowCountData; i++) {
            if (finalClass[i].equals("LULUS")) {
                jumlahSiswaLULUS = jumlahSiswaLULUS + 1;
            } else if (finalClass[i].equalsIgnoreCase("TIDAK")) {
                jumlahSiswaTIDAK = jumlahSiswaTIDAK + 1;
            }

            String nis = tablePreview.getValueAt(i, 0).toString();
            String nama = tablePreview.getValueAt(i, 1).toString();
            String jenKel = tablePreview.getValueAt(i, 2).toString();
            String Mtk1 = tablePreview.getValueAt(i, 3).toString();
            String Bindo1 = tablePreview.getValueAt(i, 4).toString();
            String Bing1 = tablePreview.getValueAt(i, 5).toString();
            String Ipa1 = tablePreview.getValueAt(i, 6).toString();
            String Mtk2 = tablePreview.getValueAt(i, 7).toString();
            String Bindo2 = tablePreview.getValueAt(i, 8).toString();
            String Bing2 = tablePreview.getValueAt(i, 9).toString();
            String Ipa2 = tablePreview.getValueAt(i, 10).toString();
            String HasilTO = tablePreview.getValueAt(i, 11).toString();
            String HasilUN = finalClass[i];
            Object[] resultData = {nis, nama, jenKel, Mtk1, Bindo1, Bing1, Ipa1, Mtk2, Bindo2, Bing2, Ipa2, HasilTO, HasilUN};
            tableModelResult.addRow(resultData);
        }
        jTabbedPane1.setSelectedIndex(1);
        labelKeterangan.setText("Hasil Klasifikasi Kelulusan UN Siswa Pada Tahun Ajaran " + jYearChooser1.getYear() + "/" + jYearChooser2.getYear() + ", dengan kriteria manual adalah sebagai berikut ");
        labelSiswaLULUS.setText(jumlahSiswaLULUS + "");
        labelSiswaTIDAK.setText(jumlahSiswaTIDAK + "");
        System.out.println("Jumlah LULUS " + jumlahSiswaLULUS);
        System.out.println("Jumlah TIDAK " + jumlahSiswaTIDAK);
    }

}
