/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Controller.ControllerDataSet;
import Controller.ControllerEvaluation;
import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelListener;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.hssf.usermodel.HSSFCell;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author RIDWAN
 */
public class FormDataset extends javax.swing.JInternalFrame {

    private DefaultTableModel tableModel;
    private JFileChooser fileChooser;
    private FileNameExtensionFilter fileNameExtensionFilter;
    private File fileName;
    private FileInputStream inputStream;
    private Object returnCellValue;
    private HSSFWorkbook workBooks;
    private HSSFSheet sheets;
    private HSSFRow rows;
    private HSSFCell cells;
    private XSSFWorkbook workBook;
    private XSSFSheet sheet;
    private XSSFRow row;
    private XSSFCell cell;

    private int rowValue;
    private int columnValue;
    private int type;
    public int countOutlier;

    public String[] columnName;
    public String[][] data;
    public String dataCell;
    public String query;
    public String tahun;
    public String nis;
    public String nama;
    public String jenisKelamin;
    public String Mtk1;
    public String Bindo1;
    public String Bing1;
    public String Ipa1;
    public String Mtk2;
    public String Bindo2;
    public String Bing2;
    public String Ipa2;
    public String Keterangan;
    public String Hasil;
    public String tahunAjaran;

    ControllerDataSet controllerDataSet;
    ControllerEvaluation controllerEvaluation;

    public FormDataset() {
        initComponents();
        setLocation(15, 30);
        initialization();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        labelTahunAjaran = new javax.swing.JLabel();
        labelPilihFile = new javax.swing.JLabel();
        txtFileDirectory = new javax.swing.JTextField();
        btnBrowse = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        thnAjaran1 = new com.toedter.calendar.JYearChooser();
        thnAjaran2 = new com.toedter.calendar.JYearChooser();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lableAllData = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePreview = new javax.swing.JTable();
        buttonImport = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        labelJumlahData = new javax.swing.JLabel();
        buttonReset = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        labelJumlahOutlier = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Dataset");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/dataset.png"))); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dataset", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        labelTahunAjaran.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelTahunAjaran.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelTahunAjaran.setText("Tahun Ajaran :");

        labelPilihFile.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelPilihFile.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelPilihFile.setText("Pilih File :");

        btnBrowse.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnBrowse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/button-browse.png"))); // NOI18N
        btnBrowse.setText("Browse..");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("/");

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/button-view.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Jumlah Keseluruhan Data Pada Dataset Saat Ini :");

        lableAllData.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lableAllData.setText("0 Data");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(labelTahunAjaran)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(thnAjaran1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(thnAjaran2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelPilihFile)
                .addGap(18, 18, 18)
                .addComponent(txtFileDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBrowse)
                .addGap(127, 127, 127)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(lableAllData)
                .addGap(63, 63, 63))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(thnAjaran1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtFileDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelPilihFile)
                                .addComponent(jLabel3)
                                .addComponent(lableAllData))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(labelTahunAjaran, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(thnAjaran2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Preview", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        tablePreview.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIS", "NAMA", "JK", "MTK1", "BINDO1", "BING1", "IPA1", "MTK2", "BINDO2", "BING2", "IPA2", "HASILTO", "HASILUN"
            }
        ));
        jScrollPane1.setViewportView(tablePreview);
        if (tablePreview.getColumnModel().getColumnCount() > 0) {
            tablePreview.getColumnModel().getColumn(0).setPreferredWidth(50);
            tablePreview.getColumnModel().getColumn(1).setMinWidth(170);
            tablePreview.getColumnModel().getColumn(1).setPreferredWidth(100);
            tablePreview.getColumnModel().getColumn(2).setPreferredWidth(1);
            tablePreview.getColumnModel().getColumn(3).setMinWidth(5);
            tablePreview.getColumnModel().getColumn(3).setPreferredWidth(5);
            tablePreview.getColumnModel().getColumn(4).setMinWidth(1);
            tablePreview.getColumnModel().getColumn(4).setPreferredWidth(10);
            tablePreview.getColumnModel().getColumn(5).setPreferredWidth(5);
            tablePreview.getColumnModel().getColumn(6).setPreferredWidth(5);
            tablePreview.getColumnModel().getColumn(7).setPreferredWidth(5);
            tablePreview.getColumnModel().getColumn(8).setPreferredWidth(5);
            tablePreview.getColumnModel().getColumn(9).setPreferredWidth(5);
            tablePreview.getColumnModel().getColumn(10).setPreferredWidth(5);
            tablePreview.getColumnModel().getColumn(11).setPreferredWidth(5);
            tablePreview.getColumnModel().getColumn(12).setMinWidth(5);
            tablePreview.getColumnModel().getColumn(12).setPreferredWidth(5);
        }

        buttonImport.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buttonImport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/button-import.png"))); // NOI18N
        buttonImport.setText("Import to Database");
        buttonImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonImportActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Jumlah Data : ");

        labelJumlahData.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelJumlahData.setForeground(new java.awt.Color(0, 153, 51));
        labelJumlahData.setText("0 Data");

        buttonReset.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buttonReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/button-reset.png"))); // NOI18N
        buttonReset.setText("Reset");
        buttonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResetActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Outlier Yang Terdeteksi :");

        labelJumlahOutlier.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelJumlahOutlier.setForeground(new java.awt.Color(204, 0, 0));
        labelJumlahOutlier.setText("0 Data");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1289, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelJumlahData, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelJumlahOutlier, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonImport)
                        .addGap(40, 40, 40)
                        .addComponent(buttonReset)
                        .addGap(525, 525, 525))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(labelJumlahData, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 5, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelJumlahOutlier, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonImport, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        try {
            fileChooser = new JFileChooser();
            fileNameExtensionFilter = new FileNameExtensionFilter("Excel File", "xls", "xlsx");
            fileChooser.setFileFilter(fileNameExtensionFilter);
            if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
                txtFileDirectory.setText(fileChooser.getSelectedFile().getAbsolutePath());
                previewFile(evt);
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Problem while load file!", "Informasi Kesalahan Upload", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnBrowseActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        FormDialogDataset formDialogDataset = new FormDialogDataset(null, true);
        formDialogDataset.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void buttonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResetActionPerformed
        // TODO add your handling code here:
        initialization();
    }//GEN-LAST:event_buttonResetActionPerformed

    private void buttonImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonImportActionPerformed
        int confirm = JOptionPane.showOptionDialog(null, "Yakin ingin meng-import data dengan Tahun Ajaran " + thnAjaran1.getYear()
                + "/" + thnAjaran2.getYear() + "?", "Import Dataser", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
        if (confirm == JOptionPane.OK_OPTION) {
            try {
                this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                controllerDataSet = new ControllerDataSet();
                controllerDataSet.importToDatabase(rowValue, columnValue, data, thnAjaran1, thnAjaran2, tableModel, countOutlier, lableAllData);
                this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
            } catch (SQLException ex) {
                Logger.getLogger(FormDataset.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_buttonImportActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton buttonImport;
    private javax.swing.JButton buttonReset;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelJumlahData;
    private javax.swing.JLabel labelJumlahOutlier;
    private javax.swing.JLabel labelPilihFile;
    private javax.swing.JLabel labelTahunAjaran;
    private javax.swing.JLabel lableAllData;
    private javax.swing.JTable tablePreview;
    private com.toedter.calendar.JYearChooser thnAjaran1;
    private com.toedter.calendar.JYearChooser thnAjaran2;
    private javax.swing.JTextField txtFileDirectory;
    // End of variables declaration//GEN-END:variables

    private void previewFile(ActionEvent evt) {
        controllerDataSet = new ControllerDataSet();
        try {
            if (txtFileDirectory.getText().endsWith(".xlsx")) {
                previewXLSX();
                buttonImport.setEnabled(true);
            } else if (txtFileDirectory.getText().endsWith(".xls")) {
                previewXLS();
                buttonImport.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(this, "File dataset harus file spreadsheet dengan ekstensi *xls atau *.xlsx!", "Error", JOptionPane.ERROR_MESSAGE, new ImageIcon("src/Gambar/fail.png"));
                btnBrowseActionPerformed(evt);
                initialization();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat memilih file, pastikan format file dataset sudah benar.\n\n"
                    + "Pesan Error :\n" + e.fillInStackTrace() + "\n\n"
                    + "Lihat menu Help untuk bantuan penggunaan.", "Error", JOptionPane.ERROR_MESSAGE, new ImageIcon("src/Gambar/fail.png"));
        }
    }

    private void previewXLSX() throws FileNotFoundException, IOException {
        /*Method Untuk Membaca Dataset dengan ekstensi .XLS*/
        fileName = new File(txtFileDirectory.getText());
        inputStream = new FileInputStream(fileName);
        workBook = new XSSFWorkbook(inputStream);
        sheet = workBook.getSheetAt(0);

        countOutlier = 0;
        rowValue = sheet.getLastRowNum() + 1;
        columnValue = sheet.getRow(0).getLastCellNum();
        data = new String[rowValue][columnValue];
        columnName = new String[columnValue];
        for (int i = 0; i < rowValue; i++) {
            row = sheet.getRow(i);
            for (int j = 0; j < columnValue; j++) {
                cell = row.getCell(j);
                type = cell.getCellType();
                returnCellValue = null;
                if (type == 0) {
                    returnCellValue = cell.getNumericCellValue();
                } else if (type == 1) {
                    returnCellValue = cell.getStringCellValue();
                }

                //dataCell = returnCellValue.toString();
                data[i][j] = returnCellValue.toString();
            }
            /*Cleansing Anomali Data (Outlier), Dimulai dari i atau baris ke 1*/
            if (i != 0) {
                double tempMtk1 = Double.parseDouble(data[i][3]);
                double tempBindo1 = Double.parseDouble(data[i][4]);
                double tempBing1 = Double.parseDouble(data[i][5]);
                double tempIpa1 = Double.parseDouble(data[i][6]);
                double tempMtk2 = Double.parseDouble(data[i][7]);
                double tempBindo2 = Double.parseDouble(data[i][8]);
                double tempBing2 = Double.parseDouble(data[i][9]);
                double tempIpa2 = Double.parseDouble(data[i][10]);
                if (tempMtk1 == 0.0 || tempBindo1 == 0.0 || tempBing1 == 0.0 || tempIpa1 == 0.0 || tempMtk2 == 0.0 || tempBindo2 == 0.0 || tempBing2 == 0.0 || tempIpa2 == 0.0) {
                    countOutlier = countOutlier + 1;
                }
            }
        }
        /*Set column name*/
        for (int i = 0; i < columnValue; i++) {
            columnName[i] = data[0][i];
        }
        /*Set table model and show file on table*/
        tableModel = new DefaultTableModel(data, columnName);
        tablePreview.setModel(tableModel);
        tableModel.removeRow(0);
        labelJumlahData.setText(tableModel.getRowCount() + " Data");
        labelJumlahOutlier.setText(countOutlier + " Data");
    }

    private void previewXLS() {
        /*Method Untuk Membaca Dataset dengan ekstensi .XLS*/
        try {
            fileName = new File(txtFileDirectory.getText());
            inputStream = new FileInputStream(fileName);
            workBooks = new HSSFWorkbook(inputStream);
            sheets = workBooks.getSheetAt(0);

            countOutlier = 0;
            rowValue = sheets.getLastRowNum() + 1;
            columnValue = sheets.getRow(0).getLastCellNum();
            data = new String[rowValue][columnValue];
            columnName = new String[columnValue];
            for (int i = 0; i < rowValue; i++) {
                rows = sheets.getRow(i);
                for (int j = 0; j < columnValue; j++) {
                    cells = rows.getCell(j);
                    type = cells.getCellType();
                    returnCellValue = null;
                    if (type == 0) {
                        returnCellValue = cells.getNumericCellValue();
                    } else if (type == 1) {
                        returnCellValue = cells.getStringCellValue();
                    }
                    data[i][j] = returnCellValue.toString();
                }
                /*Cleansing Anomali Data (Outlier), Dimulai dari i atau baris ke 1*/
                if (i != 0) {
                double tempMtk1 = Double.parseDouble(data[i][3]);
                double tempBindo1 = Double.parseDouble(data[i][4]);
                double tempBing1 = Double.parseDouble(data[i][5]);
                double tempIpa1 = Double.parseDouble(data[i][6]);
                double tempMtk2 = Double.parseDouble(data[i][7]);
                double tempBindo2 = Double.parseDouble(data[i][8]);
                double tempBing2 = Double.parseDouble(data[i][9]);
                double tempIpa2 = Double.parseDouble(data[i][10]);
                    if (tempMtk1 == 0.0 || tempBindo1 == 0.0 || tempBing1 == 0.0 || tempIpa1 == 0.0 || tempMtk2 == 0.0 || tempBindo2 == 0.0 || tempBing2 == 0.0 || tempIpa2 == 0.0) {
                        countOutlier = countOutlier + 1;
                    }
                }
            }
            /*Set column name*/
            for (int i = 0; i < columnValue; i++) {
                columnName[i] = data[0][i];
            }
            /*Set table model and show file on table*/
            tableModel = new DefaultTableModel(data, columnName);
            tablePreview.setModel(tableModel);
            tableModel.removeRow(0);
            labelJumlahData.setText(tableModel.getRowCount() + " Data");
            labelJumlahOutlier.setText(countOutlier + " Data");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FormDataset.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(FormDataset.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void initialization() {
        /*Method untuk inisialisasi form*/
        try {
            controllerDataSet = new ControllerDataSet();
            int totalData = controllerDataSet.countTotalData();
            buttonImport.setEnabled(false);
            txtFileDirectory.setText("");
            txtFileDirectory.setEditable(false);
            lableAllData.setText(totalData + " Data");
            labelJumlahData.setText(0 + " Data");
            labelJumlahOutlier.setText(0 + " Data");
            tablePreview.setModel(new javax.swing.table.DefaultTableModel(
                    new Object[][]{},
                    new String[]{
                        "NIS", "Nama", "JK", "MTK1", "BINDO1", "BING1", "IPA1", "MTK2", "BINDO2", "BING2", "IPA2", "HASILTO", "HASILUN"
                    }
            ));
        } catch (Exception e) {
            System.out.println("Form.FormDataset.initialization() : " + e);
        }

    }

}
